name: base
channels:
  - defaults
dependencies:
  - anaconda-clean=1.1.1=py310hecd8cb5_0
  - brotlipy=0.7.0=py310hca72f7f_1002
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2022.10.11=hecd8cb5_0
  - certifi=2022.12.7=py310hecd8cb5_0
  - cffi=1.15.1=py310h6c40b1e_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=22.11.1=py310hecd8cb5_4
  - conda-content-trust=0.1.3=py310hecd8cb5_0
  - conda-package-handling=1.9.0=py310hca72f7f_1
  - cryptography=38.0.1=py310hf6deb26_0
  - idna=3.4=py310hecd8cb5_0
  - libffi=3.4.2=hecd8cb5_6
  - ncurses=6.3=hca72f7f_3
  - openssl=1.1.1s=hca72f7f_0
  - pip=22.3.1=py310hecd8cb5_0
  - pluggy=1.0.0=py310hecd8cb5_1
  - pycosat=0.6.4=py310hca72f7f_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py310hecd8cb5_0
  - python=3.10.8=h218abb5_1
  - python.app=3=py310hca72f7f_0
  - readline=8.2=hca72f7f_0
  - requests=2.28.1=py310hecd8cb5_0
  - ruamel.yaml=0.17.21=py310hca72f7f_0
  - ruamel.yaml.clib=0.2.6=py310hca72f7f_1
  - setuptools=65.5.0=py310hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h880c91c_0
  - tk=8.6.12=h5d9f67b_0
  - toolz=0.12.0=py310hecd8cb5_0
  - tqdm=4.64.1=py310hecd8cb5_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.13=py310hecd8cb5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h6c40b1e_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
      - albumentations==1.3.0
      - anyio==3.6.2
      - contourpy==1.0.7
      - cycler==0.11.0
      - fastapi==0.88.0
      - fonttools==4.38.0
      - geffnet==1.0.2
      - imageio==2.24.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - matplotlib==3.6.3
      - networkx==3.0
      - numpy==1.24.1
      - opencv-python-headless==4.7.0.68
      - packaging==23.0
      - pandas==1.5.2
      - pillow==9.4.0
      - pydantic==1.10.4
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2022.7
      - pywavelets==1.4.1
      - pyyaml==6.0
      - qudida==0.0.4
      - scikit-image==0.19.3
      - scikit-learn==1.2.0
      - scipy==1.10.0
      - sniffio==1.3.0
      - starlette==0.22.0
      - threadpoolctl==3.1.0
      - tifffile==2022.10.10
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - typing-extensions==4.4.0
